export const BIO_OFFENSIVE_ROLES = Object.freeze({
  PRIMARY_INITIATOR: "Primary Initiator",
  SECONDARY_INITIATOR: "Secondary Initiator",
  PERIMETER_SPECIALIST: "Perimeter Specialist",
  DRIBBLE_PENETRATOR: "Dribble Penetrator",
  CONNECTIVE_PLAYMAKER: "Connective Playmaker",
  ROLL_AND_CUT: "Roll and Cut",
  INTERIOR_FINISHER: "Interior Finisher",
  PICK_AND_POP_BIG: "Pick and Pop Big",
  OFF_BALL_WING: "Off-Ball Wing"
});

export const BIO_DEFENSIVE_ROLES = Object.freeze({
  POINT_OF_ATTACK: "Point of Attack",
  WING_STOPPER: "Wing Stopper",
  POST_DEFENDER: "Post Defender",
  SWITCH_BIG: "Switch Big",
  CHASER: "Chaser",
  HELPSIDE_INTERCEPTOR: "Helpside Interceptor",
  HELPSIDE_SHOT_BLOCKER: "Helpside Shot Blocker",
  HELPSIDE_BODY: "Helpside Body"
});

export const BIO_OFFENSIVE_ROLE_CAPS = Object.freeze({
  [BIO_OFFENSIVE_ROLES.PRIMARY_INITIATOR]: 1,
  [BIO_OFFENSIVE_ROLES.SECONDARY_INITIATOR]: 1,
  [BIO_OFFENSIVE_ROLES.PERIMETER_SPECIALIST]: 3,
  [BIO_OFFENSIVE_ROLES.DRIBBLE_PENETRATOR]: 2,
  [BIO_OFFENSIVE_ROLES.CONNECTIVE_PLAYMAKER]: 3,
  [BIO_OFFENSIVE_ROLES.ROLL_AND_CUT]: 3,
  [BIO_OFFENSIVE_ROLES.INTERIOR_FINISHER]: 2,
  [BIO_OFFENSIVE_ROLES.PICK_AND_POP_BIG]: 2,
  [BIO_OFFENSIVE_ROLES.OFF_BALL_WING]: 3
});

export const BIO_DEFENSIVE_ROLE_CAPS = Object.freeze({
  [BIO_DEFENSIVE_ROLES.POINT_OF_ATTACK]: 1,
  [BIO_DEFENSIVE_ROLES.WING_STOPPER]: 2,
  [BIO_DEFENSIVE_ROLES.POST_DEFENDER]: 2,
  [BIO_DEFENSIVE_ROLES.SWITCH_BIG]: 2,
  [BIO_DEFENSIVE_ROLES.CHASER]: 2,
  [BIO_DEFENSIVE_ROLES.HELPSIDE_INTERCEPTOR]: 2,
  [BIO_DEFENSIVE_ROLES.HELPSIDE_SHOT_BLOCKER]: 2,
  [BIO_DEFENSIVE_ROLES.HELPSIDE_BODY]: 2
});
